# Generated by Django 4.2.11 on 2024-03-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('rest_id', models.AutoField(primary_key=True, serialize=False)),
                ('rest_name', models.CharField(max_length=255)),
                ('rest_location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_desc', models.CharField(max_length=255, null=True)),
                ('item_price', models.FloatField()),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.restaurant')),
            ],
            options={
                'db_table': 'Items',
            },
        ),
    ]
