# Generated by Django 4.2.11 on 2024-03-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_permission_role_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='permission_method',
            field=models.CharField(default='GET'),
            preserve_default=False,
        ),
    ]
